# Settings
title: "Training in Bioinformatics"
description: "Mapping the training journey in Bioinformatics"
email: "lisanna.paladin@embl.de"

# Build settings
markdown: kramdown
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template